/// Every app command (the `generate_handler!` list in src/main.rs). Listing
/// them here gives each one its own `allow-<command>` permission, and from
/// then on a window may only call the commands its capability file in
/// `capabilities/` grants (review 2026-10-08, L4). A new command must be
/// added here AND to the capability of the window that calls it; the test in
/// src/capabilities_check.rs fails otherwise.
const COMMANDS: &[&str] = &[
    "briefing_today",
    "bubble_closing",
    "chaos_debug_log",
    "chaos_drag_cursor",
    "chaos_drag_window",
    "chaos_grab_cursor",
    "chaos_grab_window",
    "chaos_note_close",
    "chaos_note_move",
    "chaos_note_open",
    "chaos_note_open_now",
    "chaos_paws",
    "chaos_paws_idle",
    "chaos_release_cursor",
    "chaos_release_window",
    "chaos_status",
    "chaos_windows",
    "claude_connect",
    "claude_disconnect",
    "clear_memory",
    "confirm_action",
    "context_debug",
    "context_status",
    "cool_model",
    "finish_setup",
    "focus_start",
    "forget_memory",
    "get_memory",
    "get_settings",
    "hide_bubble",
    "hide_panel",
    "ledge_frame",
    "ledge_watch",
    "location_search",
    "mascot_clicked",
    "open_ollama_download",
    "panel_view",
    "pull_model",
    "quit",
    "reminder_delete",
    "reset_chat",
    "resize_bubble",
    "send_message",
    "set_hitbox",
    "setup_status",
    "show_bubble",
    "show_panel",
    "start_ollama",
    "stream_copy",
    "stream_mirror",
    "stream_new_token",
    "stream_status",
    "stream_test_event",
    "update_check",
    "update_choose",
    "update_context_settings",
    "update_install",
    "update_later",
    "update_me_fake_toast",
    "update_me_set",
    "update_me_status",
    "update_me_test",
    "update_pending",
    "update_seen",
    "update_set_auto",
    "update_settings",
    "update_status",
    "update_stream_settings",
    "update_voice_settings",
    "voice_cancel",
    "voice_cancel_download",
    "voice_delete_model",
    "voice_download_model",
    "voice_hands_free",
    "voice_offer_seen",
    "voice_open_mic_settings",
    "voice_start",
    "voice_status",
    "voice_stop",
    "warm_model",
    "world_snapshot",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
