// Real-app check of biting the cursor: launches a debug build (own
// identifier, see dev/hold-check.mjs), puts the real cursor somewhere near
// him with SetCursorPos, makes him bite it (__glitch.play("biteCursor") over
// CDP) and samples his window, pose and the real cursor during the bite:
// the drawn mouth point (ANIM_BITES) must be within 2 px of the cursor tip on
// the chomp / shake frames. Also logs whether the cursor got shaken.
//
//   node dev/bite-check.mjs <target>/debug/glitch.exe dev/mouse.ps1
import { spawn, execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { chromium } from "playwright";

const [exe, mouse] = process.argv.slice(2);
const PORT = 9231;
const proc = spawn(exe, [], { env: { ...process.env, WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS: `--remote-debugging-port=${PORT}` }, stdio: "ignore" });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
let browser;
try {
  for (let i = 0; i < 60 && !browser; i++) {
    try {
      browser = await chromium.connectOverCDP(`http://localhost:${PORT}`);
    } catch {
      await sleep(500);
    }
  }
  let page;
  for (let i = 0; i < 60 && !page; i++) {
    for (const ctx of browser.contexts()) for (const p of ctx.pages()) if (p.url().includes("mascot")) page = p;
    if (!page) await sleep(500);
  }
  await page.waitForFunction(() => window.__glitch?.creature?.world, null, { timeout: 30000 });
  await page.evaluate(() => {
    const c = window.__glitch.creature;
    c.setMovement(true);
    c.brainTimer && c.clock.clearTimeout(c.brainTimer);
  });
  await sleep(1500);

  async function trial(label, offset) {
    const s0 = await page.evaluate(() => {
      const c = window.__glitch.creature;
      return { body: { x: c.body.x, y: c.body.y }, area: c.world.area, mode: c.mode };
    });
    const target = [Math.round(s0.body.x + offset[0]), Math.round(s0.body.y + offset[1])];
    execFileSync("powershell", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", mouse, "-Plan", `${target[0]},${target[1]},move,1600`]);
    await page.evaluate(() => window.__glitch.play("biteCursor"));
    const samples = [];
    const t0 = Date.now();
    while (Date.now() - t0 < 4000) {
      const s = await page.evaluate(async () => {
        const c = window.__glitch.creature;
        const v = c.view;
        const cur = await c.host.cursor();
        // The frame actually on screen (the renderer's last paint), not the animator's next one.
        return { mode: c.mode, frame: v.last?.pose.frame ?? c.animator.pose?.frame, win: c.win, feet: { x: v.placement.x, y: v.placement.y }, cur, dpr: devicePixelRatio };
      });
      samples.push({ ...s, t: Date.now() - t0 });
      await sleep(25);
    }
    const bites = await page.evaluate(() => {
      // ANIM_BITES is baked into the bundle; ask the module via the creature's helper.
      return null;
    });
    void bites;
    return { label, target, samples };
  }

  // Mouth anchors (art px), from src/sprites/anim.ts (generated by scripts/pack-sprites.py).
  const src = (await import("node:fs")).readFileSync("src/sprites/anim.ts", "utf8");
  const W = Number(/ANIM_FRAME_W = (\d+)/.exec(src)[1]);
  const H = Number(/ANIM_FRAME_H = (\d+)/.exec(src)[1]);
  const bitesBlock = src.slice(src.indexOf("ANIM_BITES"));
  const BITES = Object.fromEntries([...bitesBlock.matchAll(/(bite_cursor\d+): \[(\d+), (\d+)\]/g)].map((m) => [m[1], [Number(m[2]), Number(m[3])]]));
  const report = [];
  for (const [label, off] of [
    ["cursor above him", [20, -60]],
    ["cursor up in the air", [-40, -260]],
  ]) {
    const r = await trial(label, off);
    const errs = [];
    const cursors = new Set();
    for (const s of r.samples) {
      cursors.add(`${s.cur.x},${s.cur.y}`);
      const g = BITES[s.frame];
      if (!g || !["bite_cursor2", "bite_cursor3", "bite_cursor4"].includes(s.frame) || s.mode !== "held") continue;
      // Window CSS px x dpr = physical px; the frame's feet at placement, ART_SCALE 1.5 CSS px per art px.
      const mx = s.win.x + (s.feet.x + (g[0] - W / 2) * 1.5) * s.dpr;
      const my = s.win.y + (s.feet.y + (g[1] - H) * 1.5) * s.dpr;
      errs.push(Math.hypot(mx - s.cur.x, my - s.cur.y));
    }
    const line = `${label}: cursor set at (${r.target}), ${errs.length} chomp/shake samples, mouth to real cursor tip: max ${errs.length ? Math.max(...errs).toFixed(2) : "-"} px, mean ${errs.length ? (errs.reduce((a, b) => a + b, 0) / errs.length).toFixed(2) : "-"} px; distinct cursor positions during the bite ${cursors.size}; modes ${[...new Set(r.samples.map((s) => s.mode))].join(",")}; frames ${[...new Set(r.samples.map((s) => s.frame))].join(",")}`;
    console.log(line);
    report.push(line);
    await sleep(3500);
  }
  writeFileSync("dev/out/bite-check.txt", report.join("\n") + "\n");
} finally {
  try {
    await browser?.close();
  } catch {}
  proc.kill();
  try {
    execFileSync("taskkill", ["/PID", String(proc.pid), "/T", "/F"], { stdio: "ignore" });
  } catch {}
}
