// GENERATED by scripts/slice-hats.py - do not edit by hand.
// Hat overlays in public/sprites/hats.png: cell index and the anchor (art px
// inside the cell) that sits on the head top (see accessories.ts headTop).

export const HAT_CELL = { w: 64, h: 48 };
export const HEAD_DX = -9;
export const HEAD_HALF = 5;
export const HAT_SPRITES: Record<string, { cell: number; anchor: [number, number] }> = {"party": {cell: 0, anchor: [32, 13]}, "wizard": {cell: 1, anchor: [36, 20]}, "cap": {cell: 2, anchor: [33, 4]}, "pumpkin": {cell: 3, anchor: [32, 13]}, "santa": {cell: 4, anchor: [39, 9]}, "crown": {cell: 5, anchor: [32, 6]}, "cowboy": {cell: 6, anchor: [34, 8]}, "headphones": {cell: 7, anchor: [38, 6]}};
