"""Pack Glitch's animation frames into one sprite sheet for the app.

    python scripts/recover-grid.py      # original 16 poses -> art/puppet/src
    python scripts/slice-generated.py   # generated sheets  -> art/frames
    python scripts/pack-sprites.py      # -> public/sprites/glitch-anim.png + src/sprites/anim.ts

Every frame is CANVAS_W x CANVAS_H art px (feet on the bottom row, body
centred) and drawn by the app at a whole art-pixel grid (no smoothing).
The original 16 poses are included at the same scale under their old names
(idle0, walk0, sleep0...), so everything that used the old sheet still works.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("sg", ROOT / "scripts" / "slice-generated.py")
sg = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sg)

FRAMES = ROOT / "art" / "frames"
POSES = ROOT / "art" / "puppet" / "src"
SHEET = ROOT / "public" / "sprites" / "glitch-anim.png"
INDEX = ROOT / "src" / "sprites" / "anim.ts"
COLS = 16

#: The original sheet's poses (index in the 4x4 sheet) -> their frame name here.
LEGACY = {
    "pose_front": 0,
    "pose_side": 1,
    "pose_back": 2,
    "pose_front_alt": 3,
    "pose_walk0": 4,
    "pose_walk1": 5,
    "pose_wave": 6,
    "pose_glitch": 7,
    "pose_sit": 8,
    "pose_sleep": 9,
    "pose_happy": 10,
    "pose_laugh": 11,
    "pose_notify": 12,
    "pose_push": 13,
    "pose_think": 14,
    "pose_chaos": 15,
}


def legacy_frame(i: int) -> np.ndarray:
    a = np.array(Image.open(POSES / f"pose-{i:02d}.png").convert("RGBA"))
    a[:, :, 3] = np.where(a[:, :, 3] > 127, 255, 0)
    a = sg.trim(a)
    return sg.place(a, sg.body_x(a, "left"))


def eye_of(a: np.ndarray) -> tuple[int, int]:
    """Centre of the glitch eye: the magenta pixels' centroid (bits included), else the head's right side."""
    r, g, b = (a[:, :, i].astype(int) for i in range(3))
    m = (a[:, :, 3] > 0) & (r > 150) & (b > 180) & (g < 110)
    if m.sum() >= 3:
        ys, xs = np.where(m)
        return int(np.median(xs)), int(np.median(ys))
    ys, xs = np.where(a[:, :, 3] > 0)
    return int(xs.max() - 8), int(ys.min() + 22)


def main():
    names: list[str] = []
    imgs: list[np.ndarray] = []
    for sheet in sg.SHEETS:
        i = 0
        while (FRAMES / f"{sheet}-{i}.png").exists():
            names.append(f"{sheet}{i}")
            imgs.append(np.array(Image.open(FRAMES / f"{sheet}-{i}.png").convert("RGBA")))
            i += 1
    for name, i in LEGACY.items():
        names.append(name)
        imgs.append(legacy_frame(i))
    rows = (len(imgs) + COLS - 1) // COLS
    out = np.zeros((rows * sg.CANVAS_H, COLS * sg.CANVAS_W, 4), np.uint8)
    eyes = []
    for k, a in enumerate(imgs):
        x, y = (k % COLS) * sg.CANVAS_W, (k // COLS) * sg.CANVAS_H
        out[y : y + sg.CANVAS_H, x : x + sg.CANVAS_W] = a
        eyes.append(eye_of(a))
    SHEET.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(out, "RGBA").save(SHEET, optimize=True)
    lines = [
        "// GENERATED by scripts/pack-sprites.py - do not edit by hand.",
        "// Frame name -> index in public/sprites/glitch-anim.png, and the glitch eye per frame (art px).",
        "",
        "export const ANIM_FRAME_W = %d;" % sg.CANVAS_W,
        "export const ANIM_FRAME_H = %d;" % sg.CANVAS_H,
        "export const ANIM_INDEX: Record<string, number> = {",
        *[f"  {n}: {k}," for k, n in enumerate(names)],
        "};",
        "export const ANIM_EYES: Record<string, [number, number]> = {",
        *[f"  {n}: [{e[0]}, {e[1]}]," for n, e in zip(names, eyes)],
        "};",
        "",
    ]
    INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {SHEET.relative_to(ROOT)} ({len(imgs)} frames) and {INDEX.relative_to(ROOT)}")
    # Strip the white-background halo and close the dark outline (see clean-edges.py).
    import importlib.util

    spec = importlib.util.spec_from_file_location("clean_edges", Path(__file__).with_name("clean-edges.py"))
    ce = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ce)
    ce.clean(SHEET)


if __name__ == "__main__":
    main()
