//! Keeps `dev/ollama-check/request-template.json` identical to what Glitch
//! really sends, so the live checker (dev/ollama-check/check.mjs) tests the
//! real prompts and tools. Regenerate with:
//!   UPDATE_TEMPLATE=1 cargo test -p glitch-core --test request_template

use glitch_core::agent::{system_prompt, MEMORY_PROMPT};
use glitch_core::ai::ollama::{DEFAULT_KEEP_ALIVE, DEFAULT_NUM_CTX};
use glitch_core::ai::Message;
use glitch_core::memory::compaction_request;
use glitch_core::platform::Os;
use glitch_core::tools::specs;
use serde_json::{json, Value};

fn template() -> Value {
    let tools: Vec<Value> = specs(true)
        .iter()
        .map(|t| json!({"type": "function", "function": {"name": t.name, "description": t.description, "parameters": t.parameters}}))
        .collect();
    let compaction = compaction_request("", &[Message::user("PLACEHOLDER")]);
    json!({
        "_comment": "Generated by crates/glitch-core/tests/request_template.rs. Do not edit by hand.",
        "system_prompt": {
            "windows": system_prompt(Os::Windows),
            "macos": system_prompt(Os::MacOs),
            "linux": system_prompt(Os::Linux),
        },
        "memory_prompt": MEMORY_PROMPT,
        "tools": tools,
        "options": { "num_ctx": DEFAULT_NUM_CTX },
        "keep_alive": DEFAULT_KEEP_ALIVE,
        "compaction_system": compaction[0].content,
    })
}

#[test]
fn request_template_is_up_to_date() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../dev/ollama-check/request-template.json");
    let fresh = serde_json::to_string_pretty(&template()).unwrap() + "\n";
    if std::env::var_os("UPDATE_TEMPLATE").is_some() {
        std::fs::write(&path, &fresh).unwrap();
    }
    let on_disk = std::fs::read_to_string(&path).unwrap_or_default().replace("\r\n", "\n");
    assert_eq!(on_disk, fresh, "run: UPDATE_TEMPLATE=1 cargo test -p glitch-core --test request_template");
}
